Overwrite HTML5Video inherited methods
clappr/dash-shaka-playback pull request #87
Opened 2020-10-28 20:27 UTC by joaopaulovieira

## Summary

This PR updates `seek` and `pause` methods to overwrite `HTML5Video` Class inherits.

## Changes

* Set the current time on video element when the `seek(time)` method is called;
* Call `videoElement.pause` method when `pause` plugin method is called;

## How to test

All changes in this PR should not impact any use of the `DashShakaPlayback`.

2020-10-29 13:24 UTC, leandromoreira requested changes
LGTM but just out of curiosity, why?

2020-10-29 14:05 UTC, joaopaulovieira commented
@leandromoreira In the latest version of `clappr-core`, we add behaviors in these inherit methods via HTML5Video that probably cause problems if one playback call `super` and do other operations.

So, to avoid one bigger refactoring, we can just stop calling `super` and do the operation on the video element directly on playback implementation.

2020-10-29 14:27 UTC, pedrochamberlain approved these changes

2020-11-05 12:37 UTC, jhonatangomes approved these changes

2020-11-05 12:43 UTC, leandromoreira approved these changes

2020-11-05 13:00 UTC, merged